url: https://ajbozdar.github.io
title: Abdul-Jabbar Bozdar's Experiments
permalink: /:title/

collections:
  authors:
    output: true
defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"
