# Site settings
title: AJ.Bozdar.im
image: '/images/abdul-jabbar-home.webp'
description: > 
  Abdul-Jabbar Bozdar's Personal Website 
baseurl: ""
url: "https://imbozdar.bitbucket.io"
color_scheme: auto
content: 
  page: website
  post: article

# Author
author:
  name: Abdul-Jabbar Bozdar
  url: https://imbozdar.bitbucket.io
  # email: var+blog@postdar.com
  description: I am a computer programmer making reliable, secure, and performant 
    systems. This site is for recording my solutions to problems in computer programming.
  image: '/images/abdul-jabbar-bozdar-profile.webp'
  bio: My name is Abdul-Jabbar Bozdar. I currently work in software development, with a 
    background in Electrical and Computer Engineering. 
  # avatar: '/images/abdul-jabbar-bozdar-avatar.webp'
  twitter: 'imbozdar'
  # mastodon: 'https://fosstodon.org/@yabozdar/'
  signal: 'https://signal.me/#eu/TFme8J0vAW8TZEIss3GoMwAsIiciCrxaWbJJ-4lmYFngQQ9x6dxIfJhliolEl0UP'

# Build settings
lsi: true
markdown: kramdown
sass:
  sass_dir: _sass
  style:    compressed
include:
  - _pages
exclude: 
  - .directory
  - .ruby-lsp
  - Gemfile
  - Gemfile.lock 
  - LICENSE
  - CHANGELOG 
  - README.md 
  - test.html
  - snippets.txt 
  - images/not-in-use/

# Permalinks
permalink: /:categories/:title/
paginate:  8
paginate_path: "posts/:num/"

# Gems
plugins:
  - jekyll-paginate
  #- classifier-reborn
  #- jekyll-archives
